### ISSUE TITLE
请问：虚空终端内核该下哪个？

### ISSUE THREAD

**Issue by fyhzc** [MerlinKodo/akasha-terminal-bin#1]
你好，网上发现了这个新版clash core，我的系统是win10 64位企业版，代理工具是[Clash Nyanpasu v1.4.0](https://github.com/keiko233/clash-nyanpasu/releases/tag/v1.4.0) 请问我该下载哪个版本的虚空终端内核进行更新替换

https://github.com/MerlinKodo/akasha-terminal-bin/releases/download/latest/akasha-terminal-win-amd64.zip
https://github.com/MerlinKodo/akasha-terminal-bin/releases/download/latest/akasha-terminal-win-amd64v3.zip

是 akasha-terminal-win-amd64.zip 还是 akasha-terminal-win-amd64v3.zip

谢谢

**Comment by MerlinKodo** [comment]
https://wiki.metacubex.one/startup/faq/#_2

参考虚空终端文档，v3后缀额外支持了一些CPU特性，无v3后缀的兼容性更好，可以先下v3，可以正常运行就不用换
